customRole:
  - name: shopline-template1
    rules:
      - apiGroups: [""]
        resources: ["pods", "pods/log"]
        verbs: ["get", "watch", "list"]
      - apiGroups: [""]
        resources: ["pods/exec"]
        verbs: ["create"]

  - name: shopline-template2
    rules:
      - apiGroups: [""]
        resources: ["pods", "pods/log"]
        verbs: ["get", "watch", "list"]
